# Server Port Mapping
server.port=8080
  
  # Relational Database Connection Configurations
spring.datasource.url=jdbc:mysql://localhost:3307/cdss_elder_care?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=imakavi@123
  
  # JPA / Hibernate Lifecycle Engine Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect